### ISSUE TITLE
complete status missing for IOF V2

### ISSUE THREAD

**Issue by dfgeorge** [LukeWoodward/SplitsBrowser#32]
Version2Reader.completeStatus is not defined.
adding:

Version2Reader.completeStatus = "complete"; 

fixes the problem.

**Comment by LukeWoodward** [comment]
Thanks for spotting this bug and reporting it.

I've fixed it in a slightly different way to what you suggested.  The code that uses `.completeStatus` is in fact redundant as the status checks are done individually by the two readers, so I deleted it.  This bug should now be fixed.
