### ISSUE TITLE
UTC Start times

### ISSUE THREAD

**Issue by MrHelga** [LukeWoodward/SplitsBrowser#57]
Hi,
I have a question.. The IOF XMP v3 format requires dates and times in UTC format. However, if the local time is not GMT, then the Race graph does not show the actual start time, but GMT.
See https://helga-o.com/webres/splits/splitsbrowser.php?lauf=2323&class=01&chartType=RaceGraph&compareWith=FastestTime&selected=HE%20Tristan%20BLOEMEN&stats=SplitTime%3BTimeLoss
His start time was 9:41, but displayed as 8:41 (here in Belgium!)
Is there a way for the local time be shown?
Thanks!

**Comment by LukeWoodward** [comment]
Hi MrHelga,

I'm afraid I don't see where in the IOF standard it mandates the use of dates in UTC.

The IOF page on IOF XML v3 (http://orienteering.org/resources/it/data-standard-3-0/) has a section 
'Dates and times'.  It requires the use of dates in the ISO8601 format, but I don't see where it says that you have to use UTC for the timezone, except perhaps in the first sentence:

> Dates and times are expressed in the ISO 8601 format **yyyy-mm-ddThh:mm:ssZ**.

I think the **Z** in the above just indicates the timezone offset, which can either be `Z` for UTC or an offset such as `+01:00`.  There are example dates in the table further down this section that use non-zero timezone offsets.

So in your case, I think you would be okay to generate times in local time and optionally include the timezone offset (which SplitsBrowser ignores).  However, if I've missed something, please let me know.

Yours,

Luke

**Comment by MrHelga** [comment]
Thanks for your reply Luke. I follow your suggesting to simply omit the Z and keep the local time. The XML still validates against the XSD, so that's OK then..
